### ISSUE TITLE
SimpliSafe shows up in HomeKit but cannot control and no sensors

### ISSUE THREAD

**Issue by kitch** [graanco/homebridge-SimpliSafePlatform#15]
It's connected top homekit as I see the simplisafe alarm, but I cannot control at all and no sensors are showing up. Here is the cached accessory info and an error message from the logs. One thing im not sure of is if the security system serial number has to match the real serial number? I'm not sure how to figure that out.

```
{
    "plugin": "homebridge-simplisafeplatform",
    "platform": "homebridge-simplisafeplatform",
    "displayName": "SecuritySystem 1234567",
    "UUID": "b308379a-df21-435b-bffe-1cab6084ecc8",
    "category": 1,
    "context": {},
    "linkedServices": {
      "0000003E-0000-1000-8000-0026BB765291": [],
      "0000007E-0000-1000-8000-0026BB765291": []
    },
    "services": [
      {
        "UUID": "0000003E-0000-1000-8000-0026BB765291",
        "characteristics": [
          {
            "displayName": "Identify",
            "UUID": "00000014-0000-1000-8000-0026BB765291",
            "props": {
              "format": "bool",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pw"
              ]
            },
            "value": false,
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Manufacturer",
            "UUID": "00000020-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "SimpliSafe",
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Model",
            "UUID": "00000021-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "SecuritySystem",
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Name",
            "UUID": "00000023-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "SecuritySystem 1234567",
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Serial Number",
            "UUID": "00000030-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "1234567",
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Firmware Revision",
            "UUID": "00000052-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "",
            "eventOnlyCharacteristic": false
          }
        ]
      },
      {
        "displayName": "SimpliSafe Security System",
        "UUID": "0000007E-0000-1000-8000-0026BB765291",
        "characteristics": [
          {
            "displayName": "Name",
            "UUID": "00000023-0000-1000-8000-0026BB765291",
            "props": {
              "format": "string",
              "unit": null,
              "minValue": null,
              "maxValue": null,
              "minStep": null,
              "perms": [
                "pr"
              ]
            },
            "value": "SimpliSafe Security System",
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Security System Current State",
            "UUID": "00000066-0000-1000-8000-0026BB765291",
            "props": {
              "format": "uint8",
              "unit": null,
              "minValue": 0,
              "maxValue": 4,
              "minStep": null,
              "perms": [
                "pr",
                "ev"
              ],
              "validValues": [
                0,
                1,
                2,
                3,
                4
              ]
            },
            "value": 0,
            "eventOnlyCharacteristic": false
          },
          {
            "displayName": "Security System Target State",
            "UUID": "00000067-0000-1000-8000-0026BB765291",
            "props": {
              "format": "uint8",
              "unit": null,
              "minValue": 0,
              "maxValue": 3,
              "minStep": null,
              "perms": [
                "pr",
                "pw",
                "ev"
              ],
              "validValues": [
                0,
                1,
                2,
                3
              ]
            },
            "value": 0,
            "eventOnlyCharacteristic": false
          }
        ]
      }
    ]
  }
```

```
[7/26/2019, 1:28:05 PM] [SimpliSafe Client] publishing a new platform accessory SecuritySystem 006bfc1d
(node:66949) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isAlarming' of undefined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:105:24
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:66949) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66949) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kitch** [comment]
Figured this would be helpful as well:
```
minikitch:node_modules jakekit$ npm list
/usr/local/lib
├─┬ homebridge@0.4.50
│ ├── chalk@1.1.3 extraneous
│ ├── commander@2.8.1 extraneous
│ ├── hap-nodejs@0.4.51 extraneous
│ ├── node-persist@0.0.8 extraneous
│ ├── qrcode-terminal@0.11.0 extraneous
│ └── semver@5.0.3 extraneous
├── homebridge-simplisafeplatform@1.0.33
```

**Comment by nikonratm** [comment]
Did you specify the [correct] serial number in the config.json file?

**Comment by kitch** [comment]
I did not. Can I just use the serial number on the base station?

**Comment by kitch** [comment]
Boom! That totally did it!!

**Comment by graanco** [comment]
I am glad you guys helped!! I’ve been out of communication for a bit.
