### ISSUE TITLE
Unable to add simplisafe The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by kk0201** [graanco/homebridge-SimpliSafePlatform#21]
Hello,

I am having issue bringing up simplisafe with homebridge. I get below error.  Appreciate any help to resolve this error. I was using old one by fholgado to arm and disaram w/o any issue.

Simplisafe version 3 hardware
node version 12.9.1

(node:3422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:3422) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at checkListener (events.js:63:11)
    at ClientRequest.once (events.js:310:3)
    at new ClientRequest (_http_client.js:177:10)
    at Object.request (https.js:309:10)
    at Object.request (/usr/lib/node_modules/homebridge-smartthings/node_modules/agent-base/patch-core.js:23:20)
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:299:34
    at new Promise (<anonymous>)
    at webResponse (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:298:10)
    at API_Config (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:45:22)
    at API.request (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:243:38)
    at API.get_Sensors (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:154:33)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:125:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:3422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)

**Comment by nikonratm** [comment]
I wonder if this issue is with another plugin of yours? Looking at the error it contains a line referencing another node module (homebridge-smartthings):
`at Object.request (/usr/lib/node_modules/**homebridge-smartthings**/node_modules/agent-base/patch-core.js:23:20)`

**Comment by kk0201** [comment]
SmartThings plug-in works fine even though it throws that error. I see this issue only after installing this plugin. Thought it might be something to do with node version and downgraded to 12.5 and see same issue.

**Comment by graanco** [comment]
Weird things happen to me... the only thing I can ask is make sure the case is correct in the config file. I notice that issue trying on my beta machine....

**Comment by kk0201** [comment]
Thanks for the response @graanco .  It is working now after uninstalling some unused and old plug-ins. Upgraded node back to latest and installed the plug-in.

**Comment by graanco** [comment]
I know this is closed but it looks like someone had more time then I did ...
https://www.npmjs.com/package/homebridge-simplisafe3

**Comment by graanco** [comment]
I’ve been rewriting my code I think I almost got it. With socket....  and next I am adding in cameras. I don’t like the other guys code.
