### ISSUE TITLE
accessory not defined error

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#4]
Looks like it detected the Alarm, carbon and smoke sensor but then started getting an error. Looks like it could be with the CarbonMonoxide sensor. I know not a lot of folks have that one...
I commented out the carbon sensor in the api.js and it seemed to help but still not working completely as only the smoke detector gets loaded (not even the alarm accessory loads now. Note: I cleared the cachedAccesories).

**_Error before commenting out:_** 
[6/17/2019, 7:13:52 AM] [SimpliSafe Client] Up and monitoring.
[6/17/2019, 7:13:52 AM] Homebridge is running on port 51827.
[6/17/2019, 7:13:54 AM] [SimpliSafe Client] Updating configuration file for token
[6/17/2019, 7:13:54 AM] [SimpliSafe Client] publishing a new platform accessory CarbonMonoxideSensor 000#####
[6/17/2019, 7:13:54 AM] [SimpliSafe Client] publishing a new platform accessory SmokeSensor 000#####
(node:59300) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at SimpliSafe.addAccessory (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:178:13)
    at Object.keys.forEach.sensor (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:83:20)
    at Array.forEach (<anonymous>)
    at SimpliSafe.initPlatform (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:77:25)
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:53:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:59300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:59300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:59300) UnhandledPromiseRejectionWarning: ReferenceError: accesory is not defined
    at Characteristic.CarbonMonoxideDetected.accessory.getService.getCharacteristic.on (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:168:39)
    at Characteristic.CarbonMonoxideDetected.emit (events.js:198:13)
    at Characteristic.CarbonMonoxideDetected.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
(node:59300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**_Error after commenting out /*7:'CarbonMonoxideSensor',* (line 45) and_** /*'CarbonMonoxideSensor': 7,*/ (line 59)
[6/17/2019, 7:50:20 AM] [SimpliSafe Client] Up and monitoring.
[6/17/2019, 7:50:20 AM] Homebridge is running on port 51827.
[6/17/2019, 7:50:22 AM] [SimpliSafe Client] publishing a new platform accessory SmokeSensor 000#####
(node:61269) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at SimpliSafe.addAccessory (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:178:13)
    at Object.keys.forEach.sensor (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:83:20)
    at Array.forEach (<anonymous>)
    at SimpliSafe.initPlatform (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:77:25)
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:61:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:61269) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6/17/2019, 7:50:23 AM] [SimpliSafe Client] Refreshing Sensors Data

**Comment by graanco** [comment]
found it change line 177 to accessory.getService(Service.LeakSensor) not accessory.getService(Service.ContactSensor) in the index.js file. I'll update it soon.

**Comment by murphmr** [comment]
Updated that line - Better, loaded more accessories but still getting **accessory not defined** on refresh:
[6/17/2019, 11:01:54 AM] [SimpliSafe Client] Up and monitoring.
[6/17/2019, 11:01:54 AM] Homebridge is running on port 51827.
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory LeakSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory TemperatureSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory GlassBreakSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory MotionSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory MotionSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory MotionSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory ContactSensor ######
[6/17/2019, 11:01:56 AM] [SimpliSafe Client] publishing a new platform accessory SecuritySystem ######
[6/17/2019, 11:02:08 AM] [SimpliSafe Client] Refreshing Sensors Data
(node:69404) UnhandledPromiseRejectionWarning: ReferenceError: accesory is not defined
    at Characteristic.accessory.getService.getCharacteristic.on (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:168:39)
    at Characteristic.emit (events.js:198:13)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
(node:69404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by murphmr** [comment]
I again commented out /7:'CarbonMonoxideSensor', (line 45) and /'CarbonMonoxideSensor': 7,/ in the api.js, reset : true and restarted - now everthing is working correctly.

**Comment by graanco** [comment]
I fixed the call for C)2 sensor. and the leaksensor too... Finger crossed???? LOL the next step for me is to use the socket.io

**Comment by murphmr** [comment]
The finger crossing and code updates worked. No errors. All sensors showing up. Awesome Job!

**Comment by graanco** [comment]
Not sure if you run version 1/2 but I am tired of the your settings have been synchronized voice prompt. I hope to resolve it in patch 1.1 of this code. I will be bring in the socket.io from SimpliSafe so they will push to us the updates instead of us seeking out the status change.

**Comment by graanco** [comment]
Definitely a refresh token issue... I think I got updating it now.... That is what I get for merging like 4 version of code together...
