### ISSUE TITLE
Cannot read propery 'indexOf' of undefined

### ISSUE THREAD

**Issue by muzzymate** [graanco/homebridge-SimpliSafePlatform#9]
Updated to version 23 today and now receiving a new error that causes Homebridge to crash and end. I reviewed my config.json and thought to replace the token with the password and try again. Unfortunately, that did not seem to cause any difference.  

The error logged to the Command Prompt window is:

TypeError: Cannot read property 'indexOf' of undefined
     at ClientRequest.<anonymous> (C:\Users\chuck\AppData\Roaming\npm\node_modules\homebridge-simplisafeplatform\client\api.js:363:41)
     at Object.onceWrapper (events.js:288:20)
     at ClientRequest.emit (events.js:200:13)
     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
     at TLSSocket.socketOnData (_http_client.js:452:22)
     at TLSSocket.emit (events.js:200:13)
     at addChunk (stream_readable.js:294:12)
     at readableAddChunk (stream_readable.js:275:11)
     at TLSSocket.Readable.push (_stream_readable.js:210:10)
     at TLSWrap.onStreamRead (internal/stream_base_common.js:166:17)

**Comment by carlmiller99** [comment]
I also had that error initially, but removing the token, reentering password and resetting the accessories (reset: true) resolved it for me.

(But then I encountered the global “no response” issue.)

**Comment by muzzymate** [comment]
Thank you. Yes, resetting the Simplisafe accessories resolved the crash issue for me. I'll include that step in future troubleshooting.

**Comment by graanco** [comment]
Okay... nice to know about that. Only issue I've been see, maybe it is my attempts to figure out socket.io, but I get a login too many times and SimpliSafe will lock out my account for an hour... I do hope it is only my experience....

**Comment by muzzymate** [comment]
If the account lockout manifests as the global "no response", I'm unfortunately getting that now. I shut down my Homebridge instance and will leave it off for an hour or so. Also increased the  refresh_time variable to a higher value in case they don't like so many attempts per minute.

**Comment by graanco** [comment]
Yes good idea... I have mine set to 60 right now.. on both homes..

**Comment by graanco** [comment]
okay I think I am going to remove SS2 or less support... The delay is causing a response issue. Also I will be setting it up so there is a 30 second loop for the alarm status unless I can get the push working from socket.io

**Comment by graanco** [comment]
this issue should be gone...

**Comment by graanco** [comment]
Moving on....
https://www.npmjs.com/package/homebridge-simplisafe3
